"""Add soft delete fields

Revision ID: 14e61f5e5d3e
Revises: 
Create Date: 2026-01-16 12:30:09.620687

"""
from alembic import op
import sqlalchemy as sa


def safe_drop_index(batch_op, index_name, **kwargs):
    """Safely drop an index if it exists"""
    try:
        batch_op.drop_index(batch_op.f(index_name), **kwargs)
    except (ValueError, KeyError, Exception):
        pass  # Index doesn't exist, skip


# revision identifiers, used by Alembic.
revision = '14e61f5e5d3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('mail_recipient_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('is_published',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('kanban_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'PLANLANDI'"))
        safe_drop_index(batch_op, 'ix_job_assigned_work_date')
        safe_drop_index(batch_op, 'ix_job_project_work_date')
        safe_drop_index(batch_op, 'ix_job_subproject_work_date')
        safe_drop_index(batch_op, 'ix_job_team_work_date')
        safe_drop_index(batch_op, 'ix_job_work_date_kanban')
        batch_op.create_index(batch_op.f('ix_job_published_by_user_id'), ['published_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_job_subproject_id', 'sub_project', ['subproject_id'], ['id'])
        batch_op.create_foreign_key('fk_job_published_by_user_id', 'user', ['published_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_job_assigned_user_id', 'user', ['assigned_user_id'], ['id'])

    with op.batch_alter_table('job_feedback', schema=None) as batch_op:
        batch_op.alter_column('outcome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('isdp_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('review_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        safe_drop_index(batch_op, 'ix_job_feedback_job_submitted')
        batch_op.create_index(batch_op.f('ix_job_feedback_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_job_feedback_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_job_feedback_reviewed_by_user_id', 'user', ['reviewed_by_user_id'], ['id'])

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('durum',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Aktif'"))
        batch_op.alter_column('karsi_firma_sorumlusu',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        safe_drop_index(batch_op, 'ux_person_user_id', sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_person_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key('fk_person_firma_id', 'firma', ['firma_id'], ['id'])
        batch_op.create_foreign_key('fk_person_seviye_id', 'seviye', ['seviye_id'], ['id'])
        batch_op.create_foreign_key('fk_person_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('plan_cell', schema=None) as batch_op:
        batch_op.alter_column('lld_hhd_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('tutanak_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_plan_cell_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_foreign_key('fk_plan_cell_assigned_user_id', 'user', ['assigned_user_id'], ['id'])
        batch_op.create_foreign_key('fk_plan_cell_subproject_id', 'sub_project', ['subproject_id'], ['id'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('karsi_firma_sorumlusu',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)

    with op.batch_alter_table('team', schema=None) as batch_op:
        safe_drop_index(batch_op, 'uq_team_vehicle_id', sqlite_where=sa.text('vehicle_id IS NOT NULL'))
        batch_op.create_foreign_key('fk_team_vehicle_id', 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_super_admin',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_team_id'), ['team_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_foreign_key('fk_user_team_id', 'team', ['team_id'], ['id'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('vodafone_approval',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('vodafone_approval',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_team_id', type_='foreignkey')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_team_id'))
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('deleted_at')
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_super_admin',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_vehicle_id', type_='foreignkey')
        batch_op.create_index(batch_op.f('uq_team_vehicle_id'), ['vehicle_id'], unique=1, sqlite_where=sa.text('vehicle_id IS NOT NULL'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('karsi_firma_sorumlusu',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('plan_cell', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plan_cell_assigned_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_plan_cell_subproject_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_plan_cell_assigned_user_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('tutanak_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('lld_hhd_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('fk_person_firma_id', type_='foreignkey')
        batch_op.drop_constraint('fk_person_seviye_id', type_='foreignkey')
        batch_op.drop_constraint('fk_person_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_person_user_id'))
        batch_op.create_index(batch_op.f('ux_person_user_id'), ['user_id'], unique=1, sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('deleted_at')
        batch_op.alter_column('karsi_firma_sorumlusu',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('durum',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Aktif'"))

    with op.batch_alter_table('job_feedback', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_feedback_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_job_feedback_reviewed_by_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_job_feedback_reviewed_by_user_id'))
        batch_op.create_index(batch_op.f('ix_job_feedback_job_submitted'), ['job_id', 'submitted_at'], unique=False)
        batch_op.alter_column('review_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('isdp_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('outcome',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_subproject_id', type_='foreignkey')
        batch_op.drop_constraint('fk_job_published_by_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_job_assigned_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_job_published_by_user_id'))
        batch_op.create_index(batch_op.f('ix_job_work_date_kanban'), ['work_date', 'kanban_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_team_work_date'), ['team_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_subproject_work_date'), ['subproject_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_project_work_date'), ['project_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_assigned_work_date'), ['assigned_user_id', 'work_date'], unique=False)
        batch_op.alter_column('kanban_status',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'PLANLANDI'"))
        batch_op.alter_column('is_published',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('firma', schema=None) as batch_op:
        batch_op.alter_column('mail_recipient_name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
