"""Add deleted_at columns to person and user

Revision ID: c395c89aaa11
Revises: 14e61f5e5d3e
Create Date: 2026-01-16 13:53:07.914445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c395c89aaa11'
down_revision = '14e61f5e5d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add deleted_at columns if they don't exist
    try:
        with op.batch_alter_table('person', schema=None) as batch_op:
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
    except Exception:
        pass  # Column might already exist
    
    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
    except Exception:
        pass  # Column might already exist
    
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_assigned_work_date'))
        batch_op.drop_index(batch_op.f('ix_job_project_work_date'))
        batch_op.drop_index(batch_op.f('ix_job_subproject_work_date'))
        batch_op.drop_index(batch_op.f('ix_job_team_work_date'))
        batch_op.drop_index(batch_op.f('ix_job_work_date_kanban'))

    with op.batch_alter_table('job_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_feedback_job_submitted'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_team_vehicle_id'), sqlite_where=sa.text('vehicle_id IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove deleted_at columns
    try:
        with op.batch_alter_table('person', schema=None) as batch_op:
            batch_op.drop_column('deleted_at')
    except Exception:
        pass  # Column might not exist
    
    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_column('deleted_at')
    except Exception:
        pass  # Column might not exist
    
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_team_vehicle_id'), ['vehicle_id'], unique=1, sqlite_where=sa.text('vehicle_id IS NOT NULL'))

    with op.batch_alter_table('job_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_feedback_job_submitted'), ['job_id', 'submitted_at'], unique=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_work_date_kanban'), ['work_date', 'kanban_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_team_work_date'), ['team_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_subproject_work_date'), ['subproject_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_project_work_date'), ['project_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_assigned_work_date'), ['assigned_user_id', 'work_date'], unique=False)

    # ### end Alembic commands ###
